### ISSUE TITLE
IllegalStateException when trying to open AltN8 settings

### ISSUE THREAD

**Issue by mntnoe** [minman/altn8#20]
When trying to open AltN8 settings, I get the following error:

```
cannot reset configurable: @NotNull method altn8/ui/AlternateGenericRegexPanel$AlternateGenericPrefixRegexItemDataPanel.getConfigurationItem must not return null
java.lang.IllegalStateException: @NotNull method altn8/ui/AlternateGenericRegexPanel$AlternateGenericPrefixRegexItemDataPanel.getConfigurationItem must not return null
	at altn8.ui.AlternateGenericRegexPanel$AlternateGenericPrefixRegexItemDataPanel.getConfigurationItem(AlternateGenericRegexPanel.java:180)
	at altn8.ui.AbstractDataPanel.pullDataFrom(AbstractDataPanel.java:76)
	at altn8.ui.AlternateGenericRegexPanel.pullDataFrom(AlternateGenericRegexPanel.java:54)
	at altn8.ui.AlternateConfigurationPanel.pullDataFrom(AlternateConfigurationPanel.java:73)
	at altn8.AlternateApplicationConfigurable.reset(AlternateApplicationConfigurable.java:56)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.reset(ConfigurableCardPanel.java:123)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel$1.compute(ConfigurableCardPanel.java:80)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel$1.compute(ConfigurableCardPanel.java:65)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:895)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.create(ConfigurableCardPanel.java:65)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor$1.create(ConfigurableEditor.java:70)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor$1.create(ConfigurableEditor.java:67)
	at com.intellij.ui.CardLayoutPanel.a(CardLayoutPanel.java:88)
	at com.intellij.ui.CardLayoutPanel.a(CardLayoutPanel.java:116)
	at com.intellij.ui.CardLayoutPanel.b(CardLayoutPanel.java:132)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:318)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:417)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.g(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:779)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:457)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1693)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1635)
	at com.intellij.openapi.options.newEditor.SettingsDialog.b(SettingsDialog.java:80)
	at com.intellij.openapi.project.DumbPermissionServiceImpl.allowStartingDumbModeInside(DumbPermissionServiceImpl.java:37)
	at com.intellij.openapi.project.DumbService.allowStartingDumbModeInside(DumbService.java:294)
	at com.intellij.openapi.options.newEditor.SettingsDialog.a(SettingsDialog.java:79)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:91)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:159)
	at com.intellij.openapi.options.newEditor.SettingsDialog.show(SettingsDialog.java:78)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:91)
	at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:63)
	at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:52)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:199)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:215)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:634)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:204)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.f(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:657)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

This is the content of altn8.xml:

```
<application>
  <component name="AlternateApplicationComponent">
    <option name="freeRegexActive" value="true" />
    <option name="freeRegexItems">
      <list>
        <AlternateFreeRegexItem>
          <option name="matchExpression" value="^(.*?)\.spec\.[jt]sx?$" />
          <option name="replaceExpression" value="$1.tsx" />
        </AlternateFreeRegexItem>
        <AlternateFreeRegexItem>
          <option name="matchExpression" value="^(.*?)\.spec\.[jt]sx?$" />
          <option name="replaceExpression" value="$1.ts" />
        </AlternateFreeRegexItem>
        <AlternateFreeRegexItem>
          <option name="matchExpression" value="^(.*?)\.spec\.[jt]sx?$" />
          <option name="replaceExpression" value="$1.js" />
        </AlternateFreeRegexItem>
        <AlternateFreeRegexItem>
          <option name="matchExpression" value="^(.*?)\.[jt]sx?$" />
          <option name="replaceExpression" value="$1.spec.tsx" />
        </AlternateFreeRegexItem>
        <AlternateFreeRegexItem>
          <option name="matchExpression" value="^(.*?)\.[jt]sx?$" />
          <option name="replaceExpression" value="$1.spec.ts" />
        </AlternateFreeRegexItem>
        <AlternateFreeRegexItem>
          <option name="matchExpression" value="^(.*?)\.[jt]sx?$" />
          <option name="replaceExpression" value="$1.spec.js" />
        </AlternateFreeRegexItem>
        <AlternateFreeRegexItem>
          <option name="matchExpression" value="^(.*?)\.[jt]sx?$" />
          <option name="replaceExpression" value="$1.less" />
        </AlternateFreeRegexItem>
        <AlternateFreeRegexItem>
          <option name="matchExpression" value="^(.*?)\.less$" />
          <option name="replaceExpression" value="$1.tsx" />
        </AlternateFreeRegexItem>
        <AlternateFreeRegexItem>
          <option name="matchExpression" value="^(.*?)\.less$" />
          <option name="replaceExpression" value="$1.ts" />
        </AlternateFreeRegexItem>
        <AlternateFreeRegexItem>
          <option name="matchExpression" value="^(.*?)\.less$" />
          <option name="replaceExpression" value="$1.js" />
        </AlternateFreeRegexItem>
      </list>
    </option>
    <option name="genericRegexActive" value="false" />
    <option name="genericPrefixRegexItems" />
    <option name="genericPostfixRegexItems" />
  </component>
</application>
```

**Comment by minman** [comment]
Ok, thanks for reporting.
to workaround please close your IDE and open altn8.xml. Remove this 2 lines (near at end) and save.
```xml
<option name="genericPrefixRegexItems" />
<option name="genericPostfixRegexItems" />
```
Now you can open altn8 settings again without exception. Generic regex is disabled and the configured expressions won't match. I'll fix this in next version.

**Comment by mntnoe** [comment]
Thank you for the quick reply; your workaround worked fine :-)
