### ISSUE TITLE
Incompatibility with "JavaScript and TypeScript" plugin

### ISSUE THREAD

**Issue by JDR42** [minman/altn8#23]
I have the following "Free RegEx" definitions configured:
`^(.+)\.ts$  >>  $1.js`
`^(.+)\.js$  >>  $1.ts`

- Alt+8 from the `.ts` file results in the popup: "No corresponding file(s) found"
- Alt+8 from the `.js` file results in the exception below.

- I have isolated the problem to the "JavaScript and TypeScript" plugin by disabling other plugins.

- After disabling the plugin everything works as expected

**Env:**
```
WebStorm 2019.3   (also failed in WebStorm 2019.2)
Build #WS-193.5233.80, built on November 25, 2019
Runtime version: 11.0.4+10-b520.11 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 8
Registry: ide.max.recent.projects=500, search.everywhere.symbols=false, search.everywhere.files=false, search.everywhere.settings=true, debugger.watches.in.variables=false
Non-Bundled Plugins: Alt n 8
```

**Config:**
```
<application>
  <component name="AlternateApplicationComponent">
    <option name="freeRegexActive" value="true" />
    <option name="freeRegexItems">
      <list>
        <AlternateFreeRegexItem>
          <option name="matchExpression" value="^(.+)\.ts$" />
          <option name="replaceExpression" value="$1.js" />
        </AlternateFreeRegexItem>
        <AlternateFreeRegexItem>
          <option name="matchExpression" value="^(.+)\.js$" />
          <option name="replaceExpression" value="$1.ts" />
        </AlternateFreeRegexItem>
      </list>
    </option>
    <option name="genericRegexActive" value="false" />
  </component>
</application>
```

**Exception:**
```
java.lang.NullPointerException
	at altn8.AlternateFileAction$2.processFile(AlternateFileAction.java:116)
	at com.intellij.openapi.roots.impl.FileIndexBase$1.visitFileEx(FileIndexBase.java:63)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:292)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:324)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:324)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:324)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:324)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:324)
	at com.intellij.openapi.roots.impl.FileIndexBase.iterateContentUnderDirectory(FileIndexBase.java:44)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.iterateContentUnderDirectory(ProjectFileIndexImpl.java:24)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.iterateContent(ProjectFileIndexImpl.java:49)
	at com.intellij.openapi.roots.impl.FileIndexBase.iterateContent(FileIndexBase.java:37)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.iterateContent(ProjectFileIndexImpl.java:24)
	at altn8.AlternateFileAction.findFiles(AlternateFileAction.java:104)
	at altn8.AlternateFileAction.actionPerformed(AlternateFileAction.java:70)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:266)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:283)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:602)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$3(IdeKeyEventDispatcher.java:655)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:193)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:654)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:517)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:472)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:221)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:828)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by minman** [comment]
it looks like the *.js file is not in any module. if you search for your *.js file with Menu -> Navigate -> File (ctrl+shift+n) does webstorm find your file?

**Comment by JDR42** [comment]
When scope is set to "Project files" (upper right) the `.js` file is filtered out
When scope is set to "All files" the `.js` file shows

![image](https://user-images.githubusercontent.com/663164/70180960-00feae00-16af-11ea-9a60-8b6887a60305.png)

![image](https://user-images.githubusercontent.com/663164/70181113-49b66700-16af-11ea-8261-09cce40ec301.png)


And I am not defining any scopes or anything:

![image](https://user-images.githubusercontent.com/663164/70181248-8f732f80-16af-11ea-88c8-61bca273b406.png)


It appears the TypeScript plugin is modifying the "Project files" scope...   is there a way to include `.js` files in this "Project files" scope?

**Comment by minman** [comment]
I'm not familiar with TypeScript projects, so I don't know if there is a way to include js files.
Anyway, AltN8 can only navigate within project files. Regarding this issue I can only fix the exception.

**Comment by JDR42** [comment]
Got it, thank you very much for the insight.  And the project -- you're a stud!
